// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLWUP5ZWrTLhuoBYYGqZ9-0g6ELHC_lk',
    appId: '1:1072276128369:web:616cd5fc2934c87b4f11d0',
    messagingSenderId: '1072276128369',
    projectId: 'medicall-8aa19',
    authDomain: 'medicall-8aa19.firebaseapp.com',
    storageBucket: 'medicall-8aa19.firebasestorage.app',
    measurementId: 'G-EL0PHJKV3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8NR_vFxbpQkrlGI7T3Uq7KXIVlevABYs',
    appId: '1:1072276128369:android:155e43dd8a49550f4f11d0',
    messagingSenderId: '1072276128369',
    projectId: 'medicall-8aa19',
    storageBucket: 'medicall-8aa19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCVR_X2PIMKLqxeMo1fEe4x8bqy4o7ms',
    appId: '1:1072276128369:ios:424d365bf7d10a5b4f11d0',
    messagingSenderId: '1072276128369',
    projectId: 'medicall-8aa19',
    storageBucket: 'medicall-8aa19.firebasestorage.app',
    iosBundleId: 'com.example.myfirstApp',
  );
}
